export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
export const GET_EMPLOYEES_RESPONSE = "GET_EMPLOYEES_RESPONSE";
export const GET_EMPLOYEES_FAIL = "GET_EMPLOYEES_FAIL";

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE_RESPONSE = "GET_EMPLOYEE_RESPONSE";
export const GET_EMPLOYEE_FAIL = "GET_EMPLOYEE_FAIL";

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_RESPONSE = "ADD_EMPLOYEE_RESPONSE";
export const ADD_EMPLOYEE_FAIL = "ADD_EMPLOYEE_FAIL";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_RESPONSE = "UPDATE_EMPLOYEE_RESPONSE";
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL";

export const REMOVE_EMPLOYEE_REQUEST = "REMOVE_EMPLOYEE_REQUEST";
export const REMOVE_EMPLOYEE_RESPONSE = "REMOVE_EMPLOYEE_RESPONSE";
export const REMOVE_EMPLOYEE_FAIL = "REMOVE_EMPLOYEE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"