export const GET_OPERATORS_REQUEST = "OPERATOR_REQUEST";
export const GET_OPERATORS_SUCCESS = "GET_RESPONSE_SUCCESS";
export const GET_OPERATORS_FAIL = "GET_RESPONSE_FAIL";

export const ADD_OPERATOR_REQUEST = "ADD_OPERATOR_REQUEST"
export const ADD_OPERATOR_SUCCESS = "ADD_OPERATOR_SUCCESS"
export const ADD_OPERATOR_FAIL = "ADD_OPERATOR_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"